"""Generate gen/scdata.s: the race STAT handler chain (0:1BEC ... 0:254E, one handler per
line 0-71) as a table for the native player in hal/hle.s (same classification as the
GX4000 port: port/statchain_gen.py).
Entry (8 bytes): dc.w gb_address, next_address ; dc.w routine index ; dc.b param, param2"""
import os, sys
os.environ['GBDIS_RAW'] = '1'
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'analysis'))
sys.path.insert(0, os.path.join(ROOT, 'port'))
from statchain import handler, next_of
from statchain_gen import classify, START

ROUTINES = ['sc_grad0', 'sc_grad', 'sc_objw', 'sc_const', 'sc_objrom', 'sc_2242', 'sc_22ff',
            'sc_dma', 'sc_none', 'sc_last']


def main():
    ents, blob = [], []
    a, seen = START, set()
    while a not in seen:
        seen.add(a)
        ins = handler(a)
        body = [t for pc, t in ins if t not in ('push bc', 'pop bc')]
        nx = next_of(ins)
        if a in (0x2242, 0x22FF, 0x2209):
            nx = {0x2242: 0x228C, 0x22FF: 0x2373, 0x2209: 0x2217}[a]
        rout, p1, p2, cs = classify(a, body)
        if cs is not None:
            if cs:
                p2 = len(blob)
                for s, vals in cs:
                    blob += [s, len(vals)] + vals
                blob.append(0)
            else:
                p2 = 0xFF
        ents.append((a, rout, p1, p2, nx))
        a = nx
    assert a == START and len(ents) == 72
    L = ['; generated by statchain68.py - race STAT chain (one handler per line)', '\t.text', '\t.even',
         'sc_tab::']
    for k, (a, rout, p1, p2, nx) in enumerate(ents):
        L.append(f'\tdc.w ${a:04x},${nx:04x},{ROUTINES.index(rout) * 4}\n\tdc.b ${p1:02x},${p2:02x}   ; {k} {rout}')
    L.append('sc_end::')
    L.append('sc_rout::\n' + '\n'.join(f'\tdc.l {r}' for r in ROUTINES))
    L.append('sc_consts::              ; ocps, count, bytes ... 0')
    for i in range(0, len(blob), 16):
        L.append('\tdc.b ' + ','.join('$%02x' % v for v in blob[i:i + 16]))
    L.append('\t.even')
    open(os.path.join(HERE, 'gen', 'scdata.s'), 'w').write('\n'.join(L) + '\n')
    print('statchain68: %d handlers, %d const bytes' % (len(ents), len(blob)))


if __name__ == '__main__':
    main()
